import { z } from "zod";

export const adminSchema = z.object({
  id: z.string(),
  name: z.string(),
  email: z.email(),
  profilePictureURL: z.string().nullable(),
  profilePicturePublicId: z.string().nullable().optional(),
  isPaid: z.boolean(),
  isGuest: z.boolean().nullable(),
  isOtpVerified: z.boolean(),
  guestExpiresAt: z.string().nullable(),
  authProvider: z.string(),
  billingCycle: z.string(),
  status: z.string(),
  stripeCustomerId: z.string().nullable().optional(),
  stripeSubscriptionId: z.string().nullable().optional(),
  currentPeriodEnd: z.string().nullable(),
  role: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  termsAndConditions: z.boolean(),
  blockedUntil: z.string().nullable().optional(),
  guestIp: z.string().nullable().optional(),
  guestDeviceId: z.string().nullable().optional(),
  isResetRequest: z.boolean().optional(),
});
