import { z } from "zod";

export const adminSchema = z.object({
  id: z.string(),
  name: z.string(),
  email: z.email(),
  profilePictureURL: z.string().nullable(),
  profilePicturePublicId: z.string().nullable().optional(),
  isPaid: z.boolean(),
  isGuest: z.boolean().nullable(),
  isOtpVerified: z.boolean(),
  guestExpiresAt: z.string().nullable(),
  authProvider: z.string(),
  billingCycle: z.string(),
  status: z.string(),
  stripeCustomerId: z.string().nullable().optional(),
  stripeSubscriptionId: z.string().nullable().optional(),
  currentPeriodEnd: z.string().nullable(),
  role: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  termsAndConditions: z.boolean(),
  blockedUntil: z.string().nullable().optional(),
  guestIp: z.string().nullable().optional(),
  guestDeviceId: z.string().nullable().optional(),
  isResetRequest: z.boolean().optional(),
  isOwner: z.boolean().optional(),
  canDeleteQueries: z.boolean().nullable().optional(),
  canViewUserDetails: z.boolean().nullable().optional(),
  blockReason: z.string().nullable().optional(),
  isDeleted: z.boolean().optional(),
  deletedAt: z.string().nullable().optional(),
  purgeAt: z.string().nullable().optional(),
  deleteReason: z.string().nullable().optional(),
  deletedBy: z.string().nullable().optional(),
  flags: z.array(z.any()).optional(),
  _count: z
    .object({
      collections: z.number().optional(),
      reports: z.number().optional(),
      payments: z.number().optional(),
      contactQueries: z.number().optional(),
    })
    .optional(),
  reports: z.array(z.any()).optional(),
  collections: z.array(z.any()).optional(),
  payments: z.array(z.any()).optional(),
  contactQueries: z.array(z.any()).optional(),
});
